[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    # MQTT
    knolleary/PubSubClient

    # DHT20 sensor
    robtillaart/DHT20

    # JSON
    bblanchon/ArduinoJson

    # Display
    adafruit/Adafruit ILI9341
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit BusIO@^1.14.0
    https://github.com/adafruit/Adafruit_ImageReader.git

    # LEDs
    fastled/FastLED

    WiFiManager

    Adafruit Unified Sensor

    ricmoo/QRCode
